In [34]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

In [35]:
import webbrowser
site = "https://az.wikipedia.org/wiki/D%C3%BCnya_%C9%99halisi"
webbrowser.open(site)

True

In [41]:
text = pd.read_clipboard()
text

,İl,Dünya,Asiya,Afrika,Avropa,Latın Amerikası,Şimali Amerika,Okeaniya
0,2000,"6,115","3,698 (60.5%)",819 (13.4%),727 (11.9%),521 (8.5%),319 (5.2%),31 (0.5%)
1,2005,"6,512","3,937 (60.5%)",921 (14.1%),729 (11.2%),557 (8.6%),335 (5.1%),34 (0.5%)
2,2010,"6,909","4,167 (60.3%)","1,033 (15.0%)",733 (10.6%),589 (8.5%),352 (5.1%),36 (0.5%)
3,2015,"7,302","4,391 (60.1%)","1,153 (15.8%)",734 (10.1%),618 (8.5%),368 (5.0%),38 (0.5%)
4,2020,"7,675","4,596 (59.9%)","1,276 (16.6%)",733 (9.6%),646 (8.4%),383 (5.0%),40 (0.5%)
5,2025,"8,012","4,773 (59.6%)","1,400 (17.5%)",729 (9.1%),670 (8.4%),398 (5.0%),43 (0.5%)
6,2030,"8,309","4,917 (59.2%)","1,524 (18.3%)",723 (8.7%),690 (8.3%),410 (4.9%),45 (0.5%)
7,2035,"8,571","5,032 (58.7%)","1,647 (19.2%)",716 (8.4%),706 (8.2%),421 (4.9%),46 (0.5%)
8,2040,"8,801","5,125 (58.2%)","1,770 (20.1%)",708 (8.0%),718 (8.2%),431 (4.9%),48 (0.5%)
9,2045,"8,996","5,193 (57.7%)","1,887 (21.0%)",700 (7.8%),726 (8.1%),440 (4.9%),50 (0.6%)
10,2050,"9,150","5,231 (57.2%)","1,998 (21.8%)",691 (7.6%),729 (8.0%),448 (4.9%),51 (0.6%)